name: verify

on:
  push:
    branches-ignore:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Maven verify
        run: mvn -s ci/mvnsettings.xml verify --batch-mode
        env:
          MAGNOLIA_REPO_USER: ${{ secrets.MGNL_NEXUS_USER }}
          MAGNOLIA_REPO_PASSWORD: ${{ secrets.MGNL_NEXUS_PASS }}